Feature registration completed
Hristy-A/WorkingWithEFCore pull request #3
Opened 2022-03-25 16:04 UTC by Hristy-A

Authorization service completed. SignUp tests passed.

2022-03-25 18:24 UTC, ystiruk commented on Store.BusinessLogic/Exceptions/LogInException.cs
> +    public class LoginException : BusinessLogicException
Make file name the same as the class name

2022-03-25 18:24 UTC, ystiruk commented on Store.BusinessLogic/Exceptions/LogOutException.cs
> +    public class LogoutException : BusinessLogicException
Make file name the same as the class name

2022-03-25 18:24 UTC, ystiruk commented on Store.BusinessLogic/Exceptions/SignUpException.cs
> +    public class SignupException : BusinessLogicException
Make file name the same as the class name

2022-03-25 18:26 UTC, ystiruk commented on Store.BusinessLogic/Services/AccountService.cs
> +        private AccountService()
Why do we need private parameterless ctor here? remove?

2022-03-25 18:29 UTC, ystiruk commented on Store.BusinessLogic/Services/AccountService.cs
> +                // HACK: нужно ли проверять, имеются ли в бд юзены с одинаковыми id или login и как на реагировать?
no need to react. HACK can be removed

2022-03-25 18:29 UTC, ystiruk commented on Store.BusinessLogic/Services/AccountService.cs
> +            catch (Exception ex)
No need to catch generic exception here - if there is an exception - code shoud fail

2022-03-25 18:32 UTC, ystiruk commented on Store.BusinessLogic/Services/AccountService.cs
> +                // (done2 fixed) тут юзер может быть null, если упало до получения юзера из БД
remove comments

2022-03-25 18:32 UTC, ystiruk commented on Store.BusinessLogic/Services/AccountService.cs
>              catch (Exception ex)
dont catch exception here - code should fail

2022-03-25 18:33 UTC, ystiruk commented on Store.BusinessLogic/Services/AccountService.cs
> +            catch (Exception ex)
dont catch

2022-03-25 18:34 UTC, ystiruk commented on Store.Data/Entities/EventType.cs
> +        [Description("Successful login")]
mistype : Successfull

2022-03-25 18:35 UTC, ystiruk commented on Store.Data/Entities/EventTypeInfo.cs
> +            Description = eventType.GetDescriptionIfExsists();
mistype: Exists

2022-03-25 18:38 UTC, ystiruk commented on Store.Data/ModelConfigurations/AccountHistoryTypeConfiguration.cs
> +                .OnDelete(DeleteBehavior.Cascade);
restrict

2022-03-25 18:40 UTC, ystiruk commented on Store.Infrastructure/HashProviders/IPasswordHashProvider.cs
> +}
add newline at the end of the file

2022-03-25 18:42 UTC, ystiruk commented on Store.Infrastructure/HashProviders/VanillaHashProvider.cs
> +            byte[] salt = new byte[16];
extract magic numbers to the public constants

2022-03-25 18:43 UTC, ystiruk requested changes
Request some changes

2022-03-26 10:19 UTC, Hristy-A commented on Store.BusinessLogic/Exceptions/LogInException.cs
> +    public class LoginException : BusinessLogicException
Corrected
Enable `git config core.ignorecase false` to avoid again this
Also could be fixed using command: `git mv Name name`

2022-03-26 10:22 UTC, Hristy-A commented on Store.BusinessLogic/Services/AccountService.cs
> +        private AccountService()
Agree, deleted

2022-03-27 14:42 UTC, ystiruk reviewed
Also, you changed db (restrict, edit decription..) but didn't add migration.

2022-03-27 14:42 UTC, ystiruk commented on Store.Infrastructure/HashProviders/VanillaHashProvider.cs
> +        const int HashStartIndex = 0;
I wouldn't define constants: HashStartIndex, SaltStartIndex, TotalHashLength. They are calculated easily.

2022-03-27 14:42 UTC, ystiruk commented on Store.Infrastructure/HashProviders/VanillaHashProvider.cs
> +            for (int i = 0; i < 20; i++)
magic number

2022-03-27 14:43 UTC, ystiruk approved these changes

2022-03-27 17:50 UTC, Hristy-A commented
All comments were taken into account and mistakes were corrected👍🏻

2022-03-27 17:50 UTC, merged